Add `neo451/feed.nvim`
rockerBOO/awesome-neovim pull request #1321
Opened 2024-10-05 06:28 UTC by neo451

### Repo URL:

https://github.com/neo451/feed.nvim

### Checklist:

- [x] The plugin is specifically built for Neovim, or if it's a colorscheme, it supports treesitter syntax.
- [x] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [x] The title of the pull request is ```Add/Update/Remove `username/repo` ``` (notice the backticks around ``` `username/repo` ```) when adding a new plugin.
- [x] The description doesn't mention that it's a Neovim plugin, it's obvious from the rest of the document. No mentions of the word `plugin` unless it's related to something else. No `.. for Neovim`.
- [x] The description doesn't contain emojis.
- [x] Neovim is spelled as `Neovim` (not `nvim`, `NeoVim` or `neovim`), Vim is spelled as `Vim` (capitalized), Lua is spelled as `Lua` (capitalized), Tree-sitter is spelled as `Tree-sitter`.
- [x] Acronyms should be fully capitalized, for example `LSP`, `TS`, `YAML`, etc.

2024-10-15 10:30 UTC, tversteeg requested changes

2024-10-15 10:30 UTC, tversteeg commented on README.md
> +- [neo451/feed.nvim](https://github.com/neo451/feed.nvim) - Neovim web feed reader written in Lua (RSS, atom, json feed).
```suggestion
- [neo451/feed.nvim](https://github.com/neo451/feed.nvim) - Web feed reader written in Lua (RSS, atom, json feed).
```

2024-10-16 01:31 UTC, neo451 commented
I think it is ok to merge now @tversteeg

2024-10-16 02:52 UTC, tversteeg commented
Thanks for the PR!

2024-10-16 02:52 UTC, merged