Add `Kurama622/profile.nvim`
rockerBOO/awesome-neovim pull request #1349
Opened 2024-11-06 12:26 UTC by Kurama622

### Repo URL:

https://github.com/Kurama622/profile.nvim

### Checklist:

- [ ] The plugin is specifically built for Neovim, or if it's a colorscheme, it supports treesitter syntax.
- [ ] The lines end with a `.`. This is to conform to `awesome-list` linting and requirements.
- [ ] The title of the pull request is ```Add/Update/Remove `username/repo` ``` (notice the backticks around ``` `username/repo` ```) when adding a new plugin.
- [ ] The description doesn't mention that it's a Neovim plugin, it's obvious from the rest of the document. No mentions of the word `plugin` unless it's related to something else. No `.. for Neovim`.
- [ ] The description doesn't contain emojis.
- [ ] Neovim is spelled as `Neovim` (not `nvim`, `NeoVim` or `neovim`), Vim is spelled as `Vim` (capitalized), Lua is spelled as `Lua` (capitalized), Tree-sitter is spelled as `Tree-sitter`.
- [ ] Acronyms should be fully capitalized, for example `LSP`, `TS`, `YAML`, etc.

2024-11-16 09:25 UTC, tversteeg requested changes

2024-11-16 09:25 UTC, tversteeg commented on README.md
> +- [Kurama622/profile.nvim](https://github.com/Kurama622/profile.nvim) - Your personal homepage in Neovim.
```suggestion
- [Kurama622/profile.nvim](https://github.com/Kurama622/profile.nvim) - Your personal homepage.
```

2024-11-16 13:53 UTC, Kurama622 commented
I have already fixed it

2024-11-17 06:03 UTC, tversteeg commented
Thanks for the PR!

2024-11-17 06:03 UTC, merged